#!/bin/sh

case "$1" in
	start)
		../../usr/bin/scull_load
		../../usr/bin/module_load faulty
        modprobe hello
		;;
	stop)
		rmmod hello
		../../usr/bin/module_unload faulty
		../../usr/bin/scull_unload
		;;
    *)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
